version: 2
updates:
  # --- Python packages (pip) ---
  - package-ecosystem: "pip"
    directory: "/"                       # path containing requirements.txt
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels: ["deps", "python"]
    reviewers: ["3mcee5"]                # change/remove if you prefer CODEOWNERS only
    assignees: ["3mcee5"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      pip-patches:
        applies-to: version-updates
        update-types: ["patch"]
      pip-minors:
        applies-to: version-updates
        update-types: ["minor"]
    # Example: keep larger pandas bumps manual
    ignore:
      - dependency-name: "pandas"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

  # --- GitHub Actions (bump pinned SHAs safely) ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    labels: ["deps", "ci"]
    reviewers: ["3mcee5"]
    assignees: ["3mcee5"]
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      gha-patches:
        applies-to: version-updates
        update-types: ["patch"]
      gha-minors:
        applies-to: version-updates
        update-types: ["minor"]
